"""
Shared configuration.
"""
import json
from pathlib import Path

# MT5 connection
MT5_PATH = None
MT5_LOGIN = None
MT5_PASSWORD = None
MT5_SERVER = None

# Trading
APP_VERSION = "2026.04.24.2"
SYMBOL = "XAUUSD"
AVAILABLE_SYMBOLS = ["XAUUSD", "EURUSD", "GBPUSD", "USDJPY", "USDCHF", "AUDUSD", "USDCAD", "NZDUSD", "BTCUSD", "ETHUSD"]
MAGIC_NUMBER = 234000
DEVIATION = 20
PIP_VALUE_PER_LOT = 100

# Risk defaults
MAX_POSITIONS = 4
MAX_RISK_PCT = 0.5
MAX_DRAWDOWN_PCT = 5.0
MAX_LOT = 1.0
MIN_LOT = 0.01
DAILY_TARGET_DOLLARS = 100.0
DAILY_TARGET_ENABLED = True
DAILY_LOSS_LIMIT_PCT = 2.0
MAX_CONSECUTIVE_LOSSES = 4
MIN_TRADE_COOLDOWN = 10.0
LOSS_STREAK_PAUSE = 900

# Session (UTC)
ASIAN_START = 0
LONDON_START = 7
NY_START = 13
SESSION_BLOCK_MINUTES = 3

# Data
MAX_CANDLES = 1000
CANDLE_LIMITS = {
    "M1": 300,
    "M5": 200,
    "M15": 200,
    "H1": 200,
    "H4": 200,
}

# API
API_HOST = "127.0.0.1"
API_PORT = 8899

# Live price feed
MARKET_TICK_POLL_INTERVAL = 0.02
DASHBOARD_WS_PUSH_INTERVAL = 0.03

# Default strategy on startup
DEFAULT_STRATEGY = "AUTO"

# Tier 1 upgrades toggle
TIER1_ENABLED = True

# Manual override for strategy session gate
SESSION_OVERRIDE_ENABLED = False

# Manual overrides for hard strategy gates. Keep disabled for normal live trading.
ALL_GATES_OVERRIDE_ENABLED = False
SPREAD_GATE_OVERRIDE_ENABLED = False
COMPRESSION_GATE_OVERRIDE_ENABLED = False
EXECUTION_GATE_OVERRIDE_ENABLED = False

# Fine-grained strategy gate overrides.
TIME_GATE_OVERRIDE_ENABLED = False
SPREAD_MEAN_GATE_OVERRIDE_ENABLED = False
SPREAD_VOLATILITY_GATE_OVERRIDE_ENABLED = False
SPREAD_PERCENTILE_GATE_OVERRIDE_ENABLED = False
SPREAD_DELTA_GATE_OVERRIDE_ENABLED = False
COMPRESSION_RANGE_GATE_OVERRIDE_ENABLED = False
ATR_RISING_GATE_OVERRIDE_ENABLED = False
EXECUTION_QUALITY_GATE_OVERRIDE_ENABLED = False
TICK_DIRECTION_GATE_OVERRIDE_ENABLED = False
POST_SIGNAL_SPREAD_GATE_OVERRIDE_ENABLED = False

# Strategy spread-quality gates
SMC_SPREAD_MEAN_MAX = 0.50
SMC_SPREAD_STD_MAX = 0.05
SMC_SPREAD_PERCENTILE_MAX = 0.50
SMC_CURRENT_SPREAD_DELTA_MAX = 0.03

SCALPER_SPREAD_MEAN_MAX = 0.50
SCALPER_SPREAD_STD_MAX = 0.04
SCALPER_SPREAD_PERCENTILE_MAX = 0.50
SCALPER_CURRENT_SPREAD_DELTA_MAX = 0.03

# Compression / Range10 gates
COMPRESSION_RANGE_LOOKBACK = 10
COMPRESSION_ATR_MULTIPLIER = 1.80

# SMC gates and thresholds
SMC_THRESHOLD_WITH_TREND = 0.65
SMC_THRESHOLD_COUNTER = 0.70
SMC_THRESHOLD_COUNTER_MAX = 0.75
SMC_MIN_RR = 1.20
SMC_TIMEFRAME_EMA_SLOPE_MIN = 0.10
SMC_LTF_TICK_CONFLICT_LONG_MAX = 0.40
SMC_LTF_TICK_CONFLICT_SHORT_MIN = 0.60

# Sweep Scalper gates and thresholds
SCALPER_QUALITY_THRESHOLD = 0.65
SCALPER_ATR_MIN = 0.30
SCALPER_ATR_MAX = 5.00
SCALPER_EMA20_SLOPE_MIN = 0.05
SCALPER_BODY_RATIO_MIN = 0.40
SCALPER_TICK_DIR_THRESHOLD = 0.65
SCALPER_SWEEP_LOOKBACK = 15
SCALPER_SWEEP_TOLERANCE = 0.30
SCALPER_MAX_TRADES_SESSION = 5
SCALPER_LEVEL_COOLDOWN = 1200


_CONFIG_STATE_FILE = Path(__file__).with_name("runtime_config.json")
_PERSISTED_KEYS = {
    "MAX_POSITIONS", "MAX_RISK_PCT", "MAX_DRAWDOWN_PCT", "MAX_LOT", "MIN_LOT",
    "DAILY_TARGET_DOLLARS", "DAILY_TARGET_ENABLED", "DAILY_LOSS_LIMIT_PCT",
    "MAX_CONSECUTIVE_LOSSES", "MIN_TRADE_COOLDOWN", "LOSS_STREAK_PAUSE",
    "MARKET_TICK_POLL_INTERVAL", "DASHBOARD_WS_PUSH_INTERVAL",
    "DEFAULT_STRATEGY", "TIER1_ENABLED", "SESSION_OVERRIDE_ENABLED",
    "ALL_GATES_OVERRIDE_ENABLED", "SPREAD_GATE_OVERRIDE_ENABLED",
    "COMPRESSION_GATE_OVERRIDE_ENABLED", "EXECUTION_GATE_OVERRIDE_ENABLED",
    "TIME_GATE_OVERRIDE_ENABLED", "SPREAD_MEAN_GATE_OVERRIDE_ENABLED",
    "SPREAD_VOLATILITY_GATE_OVERRIDE_ENABLED", "SPREAD_PERCENTILE_GATE_OVERRIDE_ENABLED",
    "SPREAD_DELTA_GATE_OVERRIDE_ENABLED", "COMPRESSION_RANGE_GATE_OVERRIDE_ENABLED",
    "ATR_RISING_GATE_OVERRIDE_ENABLED", "EXECUTION_QUALITY_GATE_OVERRIDE_ENABLED",
    "TICK_DIRECTION_GATE_OVERRIDE_ENABLED", "POST_SIGNAL_SPREAD_GATE_OVERRIDE_ENABLED",
    "SMC_SPREAD_MEAN_MAX", "SMC_SPREAD_STD_MAX", "SMC_SPREAD_PERCENTILE_MAX",
    "SMC_CURRENT_SPREAD_DELTA_MAX", "SCALPER_SPREAD_MEAN_MAX",
    "SCALPER_SPREAD_STD_MAX", "SCALPER_SPREAD_PERCENTILE_MAX",
    "SCALPER_CURRENT_SPREAD_DELTA_MAX", "COMPRESSION_RANGE_LOOKBACK",
    "COMPRESSION_ATR_MULTIPLIER", "SMC_THRESHOLD_WITH_TREND",
    "SMC_THRESHOLD_COUNTER", "SMC_THRESHOLD_COUNTER_MAX", "SMC_MIN_RR",
    "SMC_TIMEFRAME_EMA_SLOPE_MIN", "SMC_LTF_TICK_CONFLICT_LONG_MAX",
    "SMC_LTF_TICK_CONFLICT_SHORT_MIN", "SCALPER_QUALITY_THRESHOLD",
    "SCALPER_ATR_MIN", "SCALPER_ATR_MAX", "SCALPER_EMA20_SLOPE_MIN",
    "SCALPER_BODY_RATIO_MIN", "SCALPER_TICK_DIR_THRESHOLD",
    "SCALPER_SWEEP_LOOKBACK", "SCALPER_SWEEP_TOLERANCE",
    "SCALPER_MAX_TRADES_SESSION", "SCALPER_LEVEL_COOLDOWN",
}
_DEFAULT_RUNTIME_CONFIG = {
    key: globals()[key]
    for key in sorted(_PERSISTED_KEYS)
    if key in globals()
}


def get_runtime_defaults() -> dict:
    """Return code defaults before runtime_config.json overrides are applied."""
    return dict(_DEFAULT_RUNTIME_CONFIG)


def load_runtime_config() -> dict:
    """Load persisted dashboard/runtime config overrides."""
    if not _CONFIG_STATE_FILE.exists():
        return {}
    try:
        data = json.loads(_CONFIG_STATE_FILE.read_text(encoding="utf-8"))
    except Exception:
        return {}
    loaded = {}
    for key, value in data.items():
        if key in _PERSISTED_KEYS and key in globals():
            globals()[key] = value
            loaded[key] = value
    return loaded


def save_runtime_config() -> dict:
    """Persist dashboard/runtime config overrides for the next restart."""
    data = {key: globals()[key] for key in sorted(_PERSISTED_KEYS) if key in globals()}
    _CONFIG_STATE_FILE.write_text(json.dumps(data, indent=2, sort_keys=True), encoding="utf-8")
    return data


load_runtime_config()
