"""
Shared configuration.
"""
import copy
import json
from datetime import datetime, timedelta, timezone
from pathlib import Path

_IST = timezone(timedelta(hours=5, minutes=30))


def _build_app_version() -> str:
    return datetime.now(_IST).strftime("%Y-%m-%d %H:%M:%S IST")


# MT5 connection
MT5_PATH = None
MT5_LOGIN = None
MT5_PASSWORD = None
MT5_SERVER = None

# Trading
APP_VERSION = _build_app_version()
SYMBOL = "XAUUSD"
AVAILABLE_SYMBOLS = ["XAUUSD", "EURUSD", "GBPUSD", "USDJPY", "USDCHF", "AUDUSD", "USDCAD", "NZDUSD", "BTCUSD", "ETHUSD"]
MAGIC_NUMBER = 234000
DEVIATION = 20
PIP_VALUE_PER_LOT = 100
TRADING_ENABLED = False
ANTI_MODE_ENABLED = False
ANTI_MODE_CONTEXT_BLOCK_ENABLED = True
ANTI_MODE_SL_MULTIPLIER = 0.8
ANTI_MODE_MAX_SL_POINTS = 3.8
ANTI_MODE_TP_MULTIPLIER = 0.5
ANTI_MODE_PROFIT_CHOKE_R = 0.12
M15_CANDLE_PROFIT_THROTTLE_ENABLED = True
M15_CANDLE_PROFIT_THROTTLE_MIN_WINS = 3
M15_CANDLE_PROFIT_THROTTLE_MIN_PNL = 2.0

# Risk defaults
MAX_POSITIONS = 3
MAX_OPEN_TRADES = 2
# When enabled, each live strategy can run independently and the global open-trade
# caps no longer block a new strategy just because another strategy already has
# a position. Duplicate protection stays per-strategy via each strategy's own
# `max_active_trades` gate.
ALLOW_CONCURRENT_STRATEGY_POSITIONS = True
# Temporary ops switch: bypass shared/global software blocks so only
# strategy-local conditions decide whether a setup can proceed. This bypasses
# centralized master-gate blocking, shared risk/cooldown/session caps, and the
# auto-trader's forced close-all / market-open guardrails. MT5/broker-side
# rejections can still happen.
TEMP_DISABLE_GLOBAL_BLOCKS = True
MAX_RISK_PCT = 1.0
INTRADAY_RISK_PCT = 0.5
SWING_RISK_PCT = 0.5
MAX_DRAWDOWN_PCT = 10.0
MAX_LOT = 0.03
MIN_LOT = 0.01
DAILY_TARGET_DOLLARS = 0.0
DAILY_TARGET_ENABLED = False
DAILY_LOSS_LIMIT_PCT = 3.0
MAX_CONSECUTIVE_LOSSES = 3
STOP_AFTER_CONSECUTIVE_LOSSES = 3
DAILY_PROFIT_LOCK = True
DAILY_PROFIT_LOCK_AFTER = 10.0
DAILY_MAX_LOSS = 0.0
DAILY_MAX_LOSS_PCT_OF_ACCOUNT = 2.0
MIN_TRADE_COOLDOWN = 120.0
LOSS_STREAK_PAUSE = 900
# Trade-count caps are optional guardrails. `0` disables count-based blocking so
# setup quality, timing, and execution conditions remain the primary filters.
SESSION_MAX_TRADES = 100
MAX_TRADES_PER_DAY = 100

# Session (UTC)
ASIAN_START = 0
LONDON_START = 7
NY_START = 13
SESSION_BLOCK_MINUTES = 3

# Strategy trade windows (UTC)
TRADE_WINDOW_LONDON_START = 7
TRADE_WINDOW_LONDON_END = 9
TRADE_WINDOW_OVERLAP_START = 12
TRADE_WINDOW_OVERLAP_END = 17

# Centralized session policy
SESSION_CENTRALIZED = True
TRADE_ASIA_SESSION = False
TRADE_CLOSED_SESSION = False
TRADE_ROLLOVER = False
PREMIUM_ONLY_ASIA = True

# Data
MAX_CANDLES = 1000
CANDLE_LIMITS = {
    "M1": 300,
    "M5": 200,
    "M15": 800,
    "M30": 400,
    "H1": 200,
    "H4": 200,
    "D1": 200,
}

# API
API_HOST = "127.0.0.1"
API_PORT = 8899

# Calendar/news filter
# When disabled, high-impact events remain visible in logs/dashboard but do not
# hard-block new entries.
CALENDAR_BLOCKING_ENABLED = True
CALENDAR_BLOCK_BEFORE_MINUTES = 15
CALENDAR_BLOCK_AFTER_MINUTES = 30

# Live price feed
MARKET_TICK_POLL_INTERVAL = 0.05
DASHBOARD_WS_PUSH_INTERVAL = 0.1

# Default strategy on startup
DEFAULT_STRATEGY = "AUTO"

# Tier 1 upgrades toggle
TIER1_ENABLED = True
TIER1_SPREAD_RECHECK_MAX_DELTA = 0.03
TIER1_EARLY_FAIL_EXIT_ENABLED = True
TIER1_EARLY_FAIL_TICKS = 15
TIER1_BLOCK_SPIKE_ENTRY = True
TIER1_MAX_ENTRY_DELAY_MS = 800

# Manual override for strategy session gate
SESSION_OVERRIDE_ENABLED = False

# Manual overrides for hard strategy gates. Keep disabled for normal live trading.
ALL_GATES_OVERRIDE_ENABLED = False
SPREAD_GATE_OVERRIDE_ENABLED = False
COMPRESSION_GATE_OVERRIDE_ENABLED = False
EXECUTION_GATE_OVERRIDE_ENABLED = False

SWEEP_SKIP_M15_CONTEXT_GATE = False

# Fine-grained strategy gate overrides.
TIME_GATE_OVERRIDE_ENABLED = False
SPREAD_MEAN_GATE_OVERRIDE_ENABLED = False
SPREAD_VOLATILITY_GATE_OVERRIDE_ENABLED = False
SPREAD_PERCENTILE_GATE_OVERRIDE_ENABLED = False
SPREAD_DELTA_GATE_OVERRIDE_ENABLED = False
COMPRESSION_RANGE_GATE_OVERRIDE_ENABLED = False
ATR_RISING_GATE_OVERRIDE_ENABLED = False
EXECUTION_QUALITY_GATE_OVERRIDE_ENABLED = False
TICK_DIRECTION_GATE_OVERRIDE_ENABLED = False
POST_SIGNAL_SPREAD_GATE_OVERRIDE_ENABLED = False

# XGBoost execution controls. Keep the model training and logging available,
# but let price-action gates remain in charge unless explicitly enabled.
XGB_BYPASS_ENABLED = False
XGB_TRAINING_ENABLED = True
XGB_BLOCKING_ENABLED = False
XGB_BLOCK_THRESHOLD = 0.35
XGB_BLEND_CONFIDENCE_ENABLED = False
XGB_LOG_CONFIDENCE_ENABLED = True

# Optional AI trade advisor. This is a bounded confirmation/veto layer that
# reviews only borderline setups that already passed deterministic gates.
AI_TRADE_ADVISOR_ENABLED = False
AI_TRADE_ADVISOR_TIMEOUT_SECONDS = 3.0
AI_TRADE_ADVISOR_MIN_SECONDS_BETWEEN_CALLS = 20
AI_TRADE_ADVISOR_MAX_CONFIDENCE = 0.72
AI_TRADE_ADVISOR_SCORE_BUFFER = 5
AI_TRADE_ADVISOR_REJECT_CONFIDENCE_MIN = 0.70
AI_TRADE_ADVISOR_FAIL_OPEN = True

# Strategy spread-quality gates
SMC_SPREAD_MEAN_MAX = 0.50
SMC_SPREAD_STD_MAX = 0.15
SMC_SPREAD_PERCENTILE_MAX = 1.00
SMC_CURRENT_SPREAD_DELTA_MAX = 0.10

SCALPER_SPREAD_MEAN_MAX = 0.50
SCALPER_SPREAD_STD_MAX = 0.16
SCALPER_SPREAD_PERCENTILE_MAX = 0.95
SCALPER_CURRENT_SPREAD_DELTA_MAX = 0.08

# Compression / Range10 gates
COMPRESSION_RANGE_LOOKBACK = 10
COMPRESSION_ATR_MULTIPLIER = 1.80

# SMC gates and thresholds
SMC_THRESHOLD_WITH_TREND = 0.70
SMC_THRESHOLD_COUNTER = 0.60
SMC_THRESHOLD_COUNTER_MAX = 0.35
SMC_MIN_RR = 1.50
SMC_MIN_SETUP_CONDITIONS = 2
SMC_REQUIRE_M5_ALIGNMENT_SHORT = True
SMC_TIMEFRAME_EMA_SLOPE_MIN = 0.08
SMC_LTF_TICK_CONFLICT_LONG_MAX = 0.30
SMC_LTF_TICK_CONFLICT_SHORT_MIN = 0.70

# SMC regime-aware threshold offsets
SMC_RANGING_THRESHOLD_OFFSET = 0.05   # added to both thresholds when regime=RANGING
SMC_TRENDING_THRESHOLD_OFFSET = 0.00  # offset when regime=TRENDING (0 = use base values)

# SMC early-fail protection (Tier1)
SMC_EARLY_FAIL_POINTS = 0.20          # default early-fail distance in points
SMC_EARLY_FAIL_RANGING = 0.15         # tighter early-fail in ranging markets
SMC_EARLY_FAIL_TRENDING = 0.25        # wider tolerance in trending markets
SMC_EARLY_FAIL_CONF_HIGH_MULT = 1.20  # multiply early-fail by this when confidence >= HIGH_CONF_THRESHOLD (more room)
SMC_EARLY_FAIL_CONF_LOW_MULT  = 0.85  # multiply early-fail by this when confidence < 0.65 (cut faster)

# Tier1 tick window for early-fail
SMC_TIER1_MIN_TICKS = 3               # do not trigger early-fail before this many ticks (noise filter)
SMC_TIER1_MAX_TICKS = 15              # stop checking early-fail after this many ticks

# Tier1 spread re-check delta (pre-send, separate from strategy spread gate)
SMC_TIER1_SPREAD_DELTA_MAX = 0.02     # max spread widening allowed between signal and order send

# Swing peak-profit capture
SWING_PEAK_CAPTURE_ENABLED = True
SWING_PEAK_CAPTURE_TRIGGER_R = 0.75   # activate once unrealized peak reaches this many R
SWING_PEAK_CAPTURE_GIVEBACK_PCT = 0.40  # close after giving back this fraction of peak profit
SWING_PEAK_CAPTURE_MIN_LOCK_R = 0.25  # once active, protect at least this many R

# SMC high-confidence scaling
SMC_HIGH_CONF_THRESHOLD = 0.75        # confidence >= this triggers high-conf mode
SMC_HIGH_CONF_RR_MULTIPLIER = 1.25    # TP distance multiplied by this in high-conf mode
SMC_HIGH_CONF_RISK_MULTIPLIER = 1.50  # lot size multiplied by this in high-conf mode (capped at MAX_LOT)

# Adaptive parameter engine — hard bounds
# These define the allowed range for live adaptive adjustments.
# The engine will never move a parameter outside these bounds.
ADAPT_THRESHOLD_WTR_MIN  = 0.70
ADAPT_THRESHOLD_WTR_MAX  = 0.70
ADAPT_THRESHOLD_CTR_MIN  = 0.60
ADAPT_THRESHOLD_CTR_MAX  = 0.60
ADAPT_MIN_RR_MIN         = 1.50
ADAPT_MIN_RR_MAX         = 1.50
ADAPT_SESSION_TRADES_MIN = 4
ADAPT_SESSION_TRADES_MAX = 4
ADAPT_COOLDOWN_MIN       = 120
ADAPT_COOLDOWN_MAX       = 120

# Sweep Scalper gates and thresholds
SCALPER_QUALITY_THRESHOLD = 0.55
SCALPER_MARGINAL_QUALITY_MAX = 0.60
SCALPER_SPEC_STRICT_MODE = True
SCALPER_ATR_MIN = 0.60
SCALPER_ATR_MAX = 5.00
SCALPER_ATR_RATIO_MAX = 1.5
SCALPER_RSI_OVERSOLD_BLOCK = 20.0
SCALPER_RSI_OVERBOUGHT_BLOCK = 80.0
SCALPER_ASIAN_ATR_MIN = 1.25
SCALPER_ASIAN_EMA_SLOPE_MIN = 0.12
SCALPER_REQUIRE_PRESSURE_ALIGNMENT = False
SCALPER_M15_TREND_REQUIRED = True
SCALPER_M15_SLOPE_MIN = 0.15
SCALPER_EMA15_SLOPE_MIN = 0.08
SCALPER_EMA20_SLOPE_MIN = 0.05
SCALPER_BODY_RATIO_MIN = 0.60
SCALPER_BODY_VS_AVG_MIN = 1.00
SCALPER_TICK_DIR_THRESHOLD = 0.70
SCALPER_SWEEP_LOOKBACK = 20
SCALPER_SWEEP_TOLERANCE = 0.25
SCALPER_HARD_SPREAD_MAX = 0.60
SCALPER_MAX_CONSECUTIVE_LOSSES = 3
SCALPER_MICRO_TP_MIN = 0.50
SCALPER_MICRO_TP_MAX = 1.00
SCALPER_MICRO_SL_MIN = 0.50
SCALPER_MICRO_SL_MAX = 0.70
SCALPER_MAX_TRADES_SESSION = 5
SCALPER_LEVEL_COOLDOWN = 1800
SCALPER_BIAS_CONSOLIDATION_ENABLED = True
SCALPER_RANGE_EDGE_ENABLED = True
SCALPER_RANGE_EDGE_LOOKBACK_CANDLES = 6
SCALPER_RANGE_EDGE_ENTRY_EDGE_ATR = 0.22
SCALPER_RANGE_EDGE_BOX_ATR_MIN = 1.15
SCALPER_RANGE_EDGE_BOX_ATR_MAX = 3.20
SCALPER_RANGE_EDGE_TP_MIN = 1.00
SCALPER_RANGE_EDGE_TP_MAX = 1.80
SCALPER_RANGE_MIN_ENTRY_VOLUME_RATIO = 0.85
SCALPER_RANGE_BODY_RATIO_MIN = 0.35
SCALPER_RANGE_TIMEOUT_SECONDS = 180
SCALPER_FIXED_LOT = 0.03
SCALPER_BIAS_CONSOLIDATION_LOOKBACK_CANDLES = 4
SCALPER_BIAS_CONSOLIDATION_RANGE_ATR_MAX = 1.25
SCALPER_BIAS_CONSOLIDATION_CANDLE_RANGE_ATR_MAX = 0.55
SCALPER_BIAS_CONSOLIDATION_CLOSE_STD_ATR_MAX = 0.35
SCALPER_BIAS_CONSOLIDATION_ENTRY_EDGE_ATR = 0.18
SCALPER_BIAS_CONSOLIDATION_SL_BUFFER = 0.25
SCALPER_BIAS_CONSOLIDATION_TP_MIN = 1.00
SCALPER_BIAS_CONSOLIDATION_TP_MAX = 2.00
SCALPER_SIDEWAYS_RANGE_CONFIRM_ENABLED = True
SCALPER_SIDEWAYS_RANGE_M30_REQUIRED = True
SCALPER_SIDEWAYS_RANGE_OVERLAP_MIN = 0.35
SCALPER_MIN_ENTRY_VOLUME_RATIO = 0.90
SCALPER_ALLOW_ASIAN_SESSION = False
SCALPER_ASIAN_MIN_ENTRY_VOLUME_RATIO = 1.0
SCALPER_ASIAN_QUALITY_THRESHOLD = 0.7
SCALPER_ASIAN_TICK_DIR_THRESHOLD = 0.72
SCALPER_ASIAN_REQUIRE_PRESSURE_ALIGNMENT = True
SMC_MIN_ENTRY_VOLUME_RATIO = 0.30
BREAKEVEN_VOLUME_LOOKBACK_CANDLES = 8
TICK_PRESSURE_WINDOW_SECONDS = 8
TICK_PRESSURE_MAX_TICKS = 250
TICK_PRESSURE_ENTRY_BLOCK_THRESHOLD = 0.35
TICK_PRESSURE_SHORT_ENTRY_VETO_THRESHOLD = 0.05
TICK_PRESSURE_BREAKEVEN_HOLD_MIN = 0.25
TICK_PRESSURE_VELOCITY_EXIT_MAX = 0.05

# M15 zone family micro-bias routing
M15_ZONE_MICRO_BIAS_ENABLED = True
M15_ZONE_MICRO_BIAS_MIN_CONFIDENCE = "MEDIUM"
M15_ZONE_MICRO_BIAS_MIN_SCORE = 40.0
M15_ZONE_ROUTE_AGAINST_BIAS_TO_INVERSE = True
M15_ZONE_BLOCK_NEUTRAL_BIAS = True
M15_ZONE_SELL_REQUIRE_SHORT_PRESSURE = True
M15_ZONE_SELL_MIN_NEGATIVE_PRESSURE_SCORE = -0.15
M15_ZONE_SELL_MIN_BODY_RATIO_IF_D1_UP = 0.85
M15_ZONE_SELL_BLOCK_IF_PRESSURE_LONG = True
M15_ZONE_BUY_REQUIRE_LONG_PRESSURE = False
M15_ZONE_BUY_MIN_BODY_RATIO_IF_D1_DOWN = 0.85
M15_ZONE_BUY_BLOCK_IF_PRESSURE_SHORT = True
M15_ZONE_LOG_MICRO_BIAS_DETAILS = True
M15_SCALP_FIXED_USD_TP_ENABLED = False
M15_SCALP_FIXED_USD_TP = 0.0
M15_ZONE_ENFORCE_SIBLING_MUTEX = True
POST_TIER1_REENTRY_COOLDOWN_SECONDS = 180.0

# Exit-management profiles
EXIT_PROFILE_SCALP_BE_TRIGGER_R = 0.22
EXIT_PROFILE_SCALP_BREAKEVEN_MIN_HOLD_SECONDS = 15
EXIT_PROFILE_SCALP_BREAKEVEN_VOLUME_HOLD_RATIO = 1.30
EXIT_PROFILE_SCALP_MIN_HOLD_SECONDS = 20
EXIT_PROFILE_SCALP_EARLY_FAIL_POINTS = 0.15
EXIT_PROFILE_SCALP_EARLY_FAIL_MIN_TICKS = 3
EXIT_PROFILE_SCALP_EARLY_FAIL_MAX_TICKS = 25
EXIT_PROFILE_SCALP_REVERSAL_ARM_R = 1.00
EXIT_PROFILE_SCALP_REVERSAL_DRAWDOWN_PCT = 0.65
EXIT_PROFILE_SCALP_REVERSAL_FLOOR_R = 0.25
EXIT_PROFILE_SCALP_PROFIT_LOCK_1_ARM_R = 0.55
EXIT_PROFILE_SCALP_PROFIT_LOCK_1_R = 0.12
EXIT_PROFILE_SCALP_PROFIT_LOCK_2_ARM_R = 0.80
EXIT_PROFILE_SCALP_PROFIT_LOCK_2_R = 0.22
EXIT_PROFILE_SCALP_TIMEOUT_SECONDS = 90
EXIT_PROFILE_SCALP_TIMEOUT_MIN_PROGRESS_R = 0.20
EXIT_PROFILE_SCALP_TRAIL_ACTIVATE_R = 1.20
EXIT_PROFILE_SCALP_TRAIL_LOCK_R = 0.40
EXIT_PROFILE_SCALP_VELOCITY_DROP_ENABLED = True

EXIT_PROFILE_SMC_BE_TRIGGER_R = 0.50
EXIT_PROFILE_SMC_BREAKEVEN_MIN_HOLD_SECONDS = 20
EXIT_PROFILE_SMC_BREAKEVEN_VOLUME_HOLD_RATIO = 1.20
EXIT_PROFILE_SMC_MIN_HOLD_SECONDS = 30
EXIT_PROFILE_SMC_EARLY_FAIL_POINTS = 0.20
EXIT_PROFILE_SMC_EARLY_FAIL_MIN_TICKS = 3
EXIT_PROFILE_SMC_EARLY_FAIL_MAX_TICKS = 15
EXIT_PROFILE_SMC_REVERSAL_ARM_R = 1.20
EXIT_PROFILE_SMC_REVERSAL_DRAWDOWN_PCT = 0.70
EXIT_PROFILE_SMC_REVERSAL_FLOOR_R = 0.35
EXIT_PROFILE_SMC_TIMEOUT_SECONDS = 120
EXIT_PROFILE_SMC_TIMEOUT_MIN_PROGRESS_R = 0.25
EXIT_PROFILE_SMC_TRAIL_ACTIVATE_R = 1.50
EXIT_PROFILE_SMC_TRAIL_LOCK_R = 0.60
EXIT_PROFILE_SMC_VELOCITY_DROP_ENABLED = False

EXIT_PROFILE_M15_BE_TRIGGER_R = 0.60
EXIT_PROFILE_M15_BREAKEVEN_MIN_HOLD_SECONDS = 30
EXIT_PROFILE_M15_BREAKEVEN_VOLUME_HOLD_RATIO = 1.10
EXIT_PROFILE_M15_MIN_HOLD_SECONDS = 60
EXIT_PROFILE_M15_EARLY_FAIL_POINTS = 0.15
EXIT_PROFILE_M15_EARLY_FAIL_MIN_TICKS = 3
EXIT_PROFILE_M15_EARLY_FAIL_MAX_TICKS = 15
EXIT_PROFILE_M15_REVERSAL_ARM_R = 1.50
EXIT_PROFILE_M15_REVERSAL_DRAWDOWN_PCT = 0.75
EXIT_PROFILE_M15_REVERSAL_FLOOR_R = 0.50
EXIT_PROFILE_M15_TIMEOUT_SECONDS = 300
EXIT_PROFILE_M15_TIMEOUT_MIN_PROGRESS_R = 0.30
EXIT_PROFILE_M15_TRAIL_ACTIVATE_R = 1.50
EXIT_PROFILE_M15_TRAIL_LOCK_R = 0.75
EXIT_PROFILE_M15_VELOCITY_DROP_ENABLED = False

EXIT_PROFILE_M15_BOUNCE_BE_TRIGGER_R = 0.12
EXIT_PROFILE_M15_BOUNCE_BREAKEVEN_MIN_HOLD_SECONDS = 8
EXIT_PROFILE_M15_BOUNCE_BREAKEVEN_VOLUME_HOLD_RATIO = 0.0
EXIT_PROFILE_M15_BOUNCE_MIN_HOLD_SECONDS = 15
EXIT_PROFILE_M15_BOUNCE_EARLY_FAIL_POINTS = 0.12
EXIT_PROFILE_M15_BOUNCE_EARLY_FAIL_MIN_TICKS = 2
EXIT_PROFILE_M15_BOUNCE_EARLY_FAIL_MAX_TICKS = 12
EXIT_PROFILE_M15_BOUNCE_REVERSAL_ARM_R = 0.80
EXIT_PROFILE_M15_BOUNCE_REVERSAL_DRAWDOWN_PCT = 0.60
EXIT_PROFILE_M15_BOUNCE_REVERSAL_FLOOR_R = 0.10
EXIT_PROFILE_M15_BOUNCE_TIMEOUT_SECONDS = 3600
EXIT_PROFILE_M15_BOUNCE_TIMEOUT_MIN_PROGRESS_R = 0.05
EXIT_PROFILE_M15_BOUNCE_TRAIL_ACTIVATE_R = 0.90
EXIT_PROFILE_M15_BOUNCE_TRAIL_LOCK_R = 0.20
EXIT_PROFILE_M15_BOUNCE_VELOCITY_DROP_ENABLED = True

# Swing Engine reversal exit parameters
SWING_ENGINE_REVERSAL_MIN_PEAK_R = 1.5       # must have reached this profit before reversal exit fires
SWING_ENGINE_REVERSAL_CANDLES_REQUIRED = 3   # consecutive counter-candles needed to confirm reversal
SWING_ENGINE_REVERSAL_BODY_THRESHOLD = 0.70  # base body ratio to qualify as a strong counter-candle
SWING_ENGINE_REVERSAL_HIGH_CONF_BODY = 0.85  # stricter body ratio when trade confidence >= HIGH_CONF_MIN
SWING_ENGINE_REVERSAL_HIGH_CONF_MIN = 0.80   # confidence threshold that triggers stricter exit rules

# Swing Engine recovery exit thresholds (profit → dip → recovery pattern)
SWING_RECOVERY_MIN_PEAK_R = 0.60    # trade must have reached this R before recovery exit can arm
SWING_RECOVERY_MIN_DIP_R = 0.25     # dip below entry must be at least this deep (not just noise)
SWING_RECOVERY_MIN_RECOVERY_R = 0.15  # recovery must reach this R before closing

# Swing Engine profit giveback floor (only close if peak was substantial)
SWING_ENGINE_GIVEBACK_MIN_PEAK_R = 2.0   # minimum peak R before giveback exit can fire
SWING_ENGINE_GIVEBACK_FLOOR_R = 0.8      # close if live_r drops this far below peak_r

# Trend Channel / Supertrend hold profile — no timeout, no early-fail, trailing SL
EXIT_PROFILE_TREND_BE_TRIGGER_R = 1.0
EXIT_PROFILE_TREND_BREAKEVEN_MIN_HOLD_SECONDS = 120
EXIT_PROFILE_TREND_BREAKEVEN_VOLUME_HOLD_RATIO = 0.0
EXIT_PROFILE_TREND_MIN_HOLD_SECONDS = 300
EXIT_PROFILE_TREND_EARLY_FAIL_POINTS = 0.0
EXIT_PROFILE_TREND_EARLY_FAIL_MIN_TICKS = 0
EXIT_PROFILE_TREND_EARLY_FAIL_MAX_TICKS = 0
EXIT_PROFILE_TREND_REVERSAL_ARM_R = 3.0
EXIT_PROFILE_TREND_REVERSAL_DRAWDOWN_PCT = 0.50
EXIT_PROFILE_TREND_REVERSAL_FLOOR_R = 1.0
EXIT_PROFILE_TREND_TIMEOUT_SECONDS = 0
EXIT_PROFILE_TREND_TIMEOUT_MIN_PROGRESS_R = 0.0
EXIT_PROFILE_TREND_TRAIL_ACTIVATE_R = 1.0
EXIT_PROFILE_TREND_TRAIL_LOCK_R = 0.5
EXIT_PROFILE_TREND_VELOCITY_DROP_ENABLED = False

# Trend Channel strategy parameters
TREND_CHANNEL_ENABLED = True
TREND_CHANNEL_TIMEFRAME = "M15"
TREND_CHANNEL_ST_PERIOD = 10
TREND_CHANNEL_ST_MULTIPLIER = 3.0
TREND_CHANNEL_MIN_CHANNEL_BARS = 20
TREND_CHANNEL_TOUCH_ATR_MULT = 0.5
TREND_CHANNEL_MAX_SPREAD = 0.60
TREND_CHANNEL_MIN_RR = 1.5
TREND_CHANNEL_ATR_MULT_SL = 0.5
TREND_CHANNEL_REQUIRE_H1_ALIGN = True

# HTF Long (higher-timeframe bias engine) strategy
# Macro trends (DXY, US10Y) are fetched automatically — no manual override needed.
HTF_LONG_ENABLED = True
HTF_LONG_MAX_SPREAD = 0.80
HTF_LONG_MIN_RR = 1.8
HTF_LONG_MANUAL_BIAS_ENABLED = False

# HTF Short (higher-timeframe bias engine) strategy — SELL only mirror of HTF_LONG
HTF_SHORT_ENABLED = True
HTF_SHORT_MAX_SPREAD = 0.80
HTF_SHORT_MIN_RR = 1.8
# Operator override: when enabled, HTF_SHORT can use a guarded structure-based
# fallback even if macro/weekly filters are not fully aligned yet.
HTF_SHORT_MANUAL_BIAS_ENABLED = False


def get_exit_profile_config(name: str) -> dict:
    profile_name = str(name or "").strip().lower()
    profiles = {
        "scalp": {
            "profile_name": "scalp",
            "be_trigger_r": EXIT_PROFILE_SCALP_BE_TRIGGER_R,
            "breakeven_min_hold_seconds": EXIT_PROFILE_SCALP_BREAKEVEN_MIN_HOLD_SECONDS,
            "breakeven_volume_hold_ratio": EXIT_PROFILE_SCALP_BREAKEVEN_VOLUME_HOLD_RATIO,
            "min_hold_seconds": EXIT_PROFILE_SCALP_MIN_HOLD_SECONDS,
            "early_fail_points": EXIT_PROFILE_SCALP_EARLY_FAIL_POINTS,
            "early_fail_min_ticks": EXIT_PROFILE_SCALP_EARLY_FAIL_MIN_TICKS,
            "early_fail_max_ticks": EXIT_PROFILE_SCALP_EARLY_FAIL_MAX_TICKS,
            "reversal_arm_r": EXIT_PROFILE_SCALP_REVERSAL_ARM_R,
            "reversal_drawdown_pct": EXIT_PROFILE_SCALP_REVERSAL_DRAWDOWN_PCT,
            "reversal_floor_r": EXIT_PROFILE_SCALP_REVERSAL_FLOOR_R,
            "profit_lock_1_arm_r": EXIT_PROFILE_SCALP_PROFIT_LOCK_1_ARM_R,
            "profit_lock_1_r": EXIT_PROFILE_SCALP_PROFIT_LOCK_1_R,
            "profit_lock_2_arm_r": EXIT_PROFILE_SCALP_PROFIT_LOCK_2_ARM_R,
            "profit_lock_2_r": EXIT_PROFILE_SCALP_PROFIT_LOCK_2_R,
            "timeout_seconds": EXIT_PROFILE_SCALP_TIMEOUT_SECONDS,
            "timeout_min_progress_r": EXIT_PROFILE_SCALP_TIMEOUT_MIN_PROGRESS_R,
            "trail_activate_r": EXIT_PROFILE_SCALP_TRAIL_ACTIVATE_R,
            "trail_lock_r": EXIT_PROFILE_SCALP_TRAIL_LOCK_R,
            "velocity_drop_enabled": EXIT_PROFILE_SCALP_VELOCITY_DROP_ENABLED,
        },
        "swing_fast": {
            "profile_name": "swing_fast",
            "be_trigger_r": EXIT_PROFILE_SMC_BE_TRIGGER_R,
            "breakeven_min_hold_seconds": EXIT_PROFILE_SMC_BREAKEVEN_MIN_HOLD_SECONDS,
            "breakeven_volume_hold_ratio": EXIT_PROFILE_SMC_BREAKEVEN_VOLUME_HOLD_RATIO,
            "min_hold_seconds": EXIT_PROFILE_SMC_MIN_HOLD_SECONDS,
            "early_fail_points": EXIT_PROFILE_SMC_EARLY_FAIL_POINTS,
            "early_fail_min_ticks": EXIT_PROFILE_SMC_EARLY_FAIL_MIN_TICKS,
            "early_fail_max_ticks": EXIT_PROFILE_SMC_EARLY_FAIL_MAX_TICKS,
            "reversal_arm_r": EXIT_PROFILE_SMC_REVERSAL_ARM_R,
            "reversal_drawdown_pct": EXIT_PROFILE_SMC_REVERSAL_DRAWDOWN_PCT,
            "reversal_floor_r": EXIT_PROFILE_SMC_REVERSAL_FLOOR_R,
            "timeout_seconds": EXIT_PROFILE_SMC_TIMEOUT_SECONDS,
            "timeout_min_progress_r": EXIT_PROFILE_SMC_TIMEOUT_MIN_PROGRESS_R,
            "trail_activate_r": EXIT_PROFILE_SMC_TRAIL_ACTIVATE_R,
            "trail_lock_r": EXIT_PROFILE_SMC_TRAIL_LOCK_R,
            "velocity_drop_enabled": EXIT_PROFILE_SMC_VELOCITY_DROP_ENABLED,
        },
        "m15_mean_reversion_fast": {
            "profile_name": "m15_mean_reversion_fast",
            "be_trigger_r": EXIT_PROFILE_M15_BOUNCE_BE_TRIGGER_R,
            "breakeven_min_hold_seconds": EXIT_PROFILE_M15_BOUNCE_BREAKEVEN_MIN_HOLD_SECONDS,
            "breakeven_volume_hold_ratio": EXIT_PROFILE_M15_BOUNCE_BREAKEVEN_VOLUME_HOLD_RATIO,
            "min_hold_seconds": EXIT_PROFILE_M15_BOUNCE_MIN_HOLD_SECONDS,
            "early_fail_points": EXIT_PROFILE_M15_BOUNCE_EARLY_FAIL_POINTS,
            "early_fail_min_ticks": EXIT_PROFILE_M15_BOUNCE_EARLY_FAIL_MIN_TICKS,
            "early_fail_max_ticks": EXIT_PROFILE_M15_BOUNCE_EARLY_FAIL_MAX_TICKS,
            "reversal_arm_r": EXIT_PROFILE_M15_BOUNCE_REVERSAL_ARM_R,
            "reversal_drawdown_pct": EXIT_PROFILE_M15_BOUNCE_REVERSAL_DRAWDOWN_PCT,
            "reversal_floor_r": EXIT_PROFILE_M15_BOUNCE_REVERSAL_FLOOR_R,
            "timeout_seconds": EXIT_PROFILE_M15_BOUNCE_TIMEOUT_SECONDS,
            "timeout_min_progress_r": EXIT_PROFILE_M15_BOUNCE_TIMEOUT_MIN_PROGRESS_R,
            "trail_activate_r": EXIT_PROFILE_M15_BOUNCE_TRAIL_ACTIVATE_R,
            "trail_lock_r": EXIT_PROFILE_M15_BOUNCE_TRAIL_LOCK_R,
            "velocity_drop_enabled": EXIT_PROFILE_M15_BOUNCE_VELOCITY_DROP_ENABLED,
        },
        "m15_zone_scalp": {
            "profile_name": "m15_zone_scalp",
            "be_trigger_r": EXIT_PROFILE_M15_BOUNCE_BE_TRIGGER_R,
            "breakeven_min_hold_seconds": EXIT_PROFILE_M15_BOUNCE_BREAKEVEN_MIN_HOLD_SECONDS,
            "breakeven_volume_hold_ratio": EXIT_PROFILE_M15_BOUNCE_BREAKEVEN_VOLUME_HOLD_RATIO,
            "min_hold_seconds": EXIT_PROFILE_M15_BOUNCE_MIN_HOLD_SECONDS,
            "early_fail_points": EXIT_PROFILE_M15_BOUNCE_EARLY_FAIL_POINTS,
            "early_fail_min_ticks": EXIT_PROFILE_M15_BOUNCE_EARLY_FAIL_MIN_TICKS,
            "early_fail_max_ticks": EXIT_PROFILE_M15_BOUNCE_EARLY_FAIL_MAX_TICKS,
            "reversal_arm_r": EXIT_PROFILE_M15_BOUNCE_REVERSAL_ARM_R,
            "reversal_drawdown_pct": EXIT_PROFILE_M15_BOUNCE_REVERSAL_DRAWDOWN_PCT,
            "reversal_floor_r": EXIT_PROFILE_M15_BOUNCE_REVERSAL_FLOOR_R,
            "profit_lock_1_arm_r": EXIT_PROFILE_SCALP_PROFIT_LOCK_1_ARM_R,
            "profit_lock_1_r": EXIT_PROFILE_SCALP_PROFIT_LOCK_1_R,
            "profit_lock_2_arm_r": EXIT_PROFILE_SCALP_PROFIT_LOCK_2_ARM_R,
            "profit_lock_2_r": EXIT_PROFILE_SCALP_PROFIT_LOCK_2_R,
            "timeout_seconds": EXIT_PROFILE_M15_BOUNCE_TIMEOUT_SECONDS,
            "timeout_min_progress_r": EXIT_PROFILE_M15_BOUNCE_TIMEOUT_MIN_PROGRESS_R,
            "trail_activate_r": EXIT_PROFILE_M15_BOUNCE_TRAIL_ACTIVATE_R,
            "trail_lock_r": EXIT_PROFILE_M15_BOUNCE_TRAIL_LOCK_R,
            "velocity_drop_enabled": EXIT_PROFILE_M15_BOUNCE_VELOCITY_DROP_ENABLED,
        },
        "m15_scalp_deep": {
            "profile_name": "m15_scalp_deep",
            "be_trigger_r": 0.18,
            "breakeven_min_hold_seconds": 12,
            "breakeven_volume_hold_ratio": 0.0,
            "min_hold_seconds": 12,
            "early_fail_points": 0.10,
            "early_fail_min_ticks": 2,
            "early_fail_max_ticks": 10,
            "reversal_arm_r": 0.75,
            "reversal_drawdown_pct": 0.55,
            "reversal_floor_r": 0.12,
            "profit_lock_1_arm_r": EXIT_PROFILE_SCALP_PROFIT_LOCK_1_ARM_R,
            "profit_lock_1_r": EXIT_PROFILE_SCALP_PROFIT_LOCK_1_R,
            "profit_lock_2_arm_r": EXIT_PROFILE_SCALP_PROFIT_LOCK_2_ARM_R,
            "profit_lock_2_r": EXIT_PROFILE_SCALP_PROFIT_LOCK_2_R,
            "timeout_seconds": 1200,
            "timeout_min_progress_r": 0.08,
            "trail_activate_r": 0.85,
            "trail_lock_r": 0.18,
            "velocity_drop_enabled": True,
        },
        "swing_trend": {
            "profile_name": "swing_trend",
            "be_trigger_r": EXIT_PROFILE_TREND_BE_TRIGGER_R,
            "breakeven_min_hold_seconds": EXIT_PROFILE_TREND_BREAKEVEN_MIN_HOLD_SECONDS,
            "breakeven_volume_hold_ratio": EXIT_PROFILE_TREND_BREAKEVEN_VOLUME_HOLD_RATIO,
            "min_hold_seconds": EXIT_PROFILE_TREND_MIN_HOLD_SECONDS,
            "early_fail_points": EXIT_PROFILE_TREND_EARLY_FAIL_POINTS,
            "early_fail_min_ticks": EXIT_PROFILE_TREND_EARLY_FAIL_MIN_TICKS,
            "early_fail_max_ticks": EXIT_PROFILE_TREND_EARLY_FAIL_MAX_TICKS,
            "reversal_arm_r": EXIT_PROFILE_TREND_REVERSAL_ARM_R,
            "reversal_drawdown_pct": EXIT_PROFILE_TREND_REVERSAL_DRAWDOWN_PCT,
            "reversal_floor_r": EXIT_PROFILE_TREND_REVERSAL_FLOOR_R,
            "timeout_seconds": EXIT_PROFILE_TREND_TIMEOUT_SECONDS,
            "timeout_min_progress_r": EXIT_PROFILE_TREND_TIMEOUT_MIN_PROGRESS_R,
            "trail_activate_r": EXIT_PROFILE_TREND_TRAIL_ACTIVATE_R,
            "trail_lock_r": EXIT_PROFILE_TREND_TRAIL_LOCK_R,
            "velocity_drop_enabled": EXIT_PROFILE_TREND_VELOCITY_DROP_ENABLED,
        },
        "swing_engine": {
            "profile_name": "swing_engine",
            "be_trigger_r": 0.0,
            "breakeven_min_hold_seconds": 0,
            "breakeven_volume_hold_ratio": 0.0,
            "min_hold_seconds": 0,
            "early_fail_points": 0.0,
            "early_fail_min_ticks": 0,
            "early_fail_max_ticks": 0,
            "reversal_arm_r": 0.0,
            "reversal_drawdown_pct": 0.0,
            "reversal_floor_r": 0.0,
            "profit_lock_1_arm_r": 0.0,
            "profit_lock_1_r": 0.0,
            "profit_lock_2_arm_r": 0.0,
            "profit_lock_2_r": 0.0,
            "timeout_seconds": 0,
            "timeout_min_progress_r": 0.0,
            "trail_activate_r": 0.0,
            "trail_lock_r": 0.0,
            "velocity_drop_enabled": False,
        },
    }
    return dict(profiles.get(profile_name, profiles["swing_fast"]))

# M15 support/resistance rejection strategy
M15_SR_ENABLED = True
M15_SR_AS_CONTEXT_ONLY = False
M15_SR_LOOKBACK_HOURS = 2
M15_SR_FALLBACK_LOOKBACK_HOURS = 6
M15_SR_EXTENDED_LOOKBACK_HOURS = 168
M15_SR_MIN_TOUCHES = 2
M15_SR_ZONE_ATR_MULT = 0.25
M15_SR_ENTRY_BUFFER_ATR = 0.10
M15_SR_SL_BUFFER_ATR = 0.35
M15_SR_MIN_RR = 1.40
M15_SR_DEFAULT_RR = 1.60
M15_SR_MAX_SPREAD = 0.55
M15_SR_MAX_TRADES_PER_DAY = 0
M15_SR_COOLDOWN_CANDLES = 3
M15_SR_BLOCK_AFTER_SPIKE_CANDLES = 2
M15_SR_SPIKE_RANGE_ATR_MULT = 2.0
M15_SR_SPIKE_VOLUME_MULT = 1.8
M15_SR_MAX_DISTANCE_FROM_ZONE_ATR = 0.25
M15_SR_REQUIRE_CANDLE_CONFIRMATION = True
M15_SR_SPIKE_ZONE_BYPASS = False
M15_SR_H1_FILTER_ENABLED = True
M15_SR_BLOCK_BUY_WHEN_H1_DOWN = True
M15_SR_BLOCK_SELL_WHEN_H1_UP = True
M15_SR_BLOCK_NORMAL_BUY_WHEN_M15_DOWN = True
M15_SR_BLOCK_NORMAL_SELL_WHEN_M15_UP = True
M15_SR_COUNTER_BIAS_MODE_ENABLED = True
M15_SR_ALLOW_COUNTER_BIAS_ONLY_AS_BOUNCE = True
M15_SR_REQUIRE_TRUE_REVERSAL_FOR_H1_OPPOSITE = True
M15_SR_TICK_MIN_TREND_ALIGNED = -0.10
M15_SR_TICK_MIN_COUNTER_BIAS_BOUNCE = 0.25
M15_SR_TICK_MIN_ASIAN_COUNTER_BIAS_BOUNCE = 0.30
M15_SR_TICK_MIN_TRUE_REVERSAL = 0.40
M15_SR_BLOCK_COUNTER_BIAS_BUY_IF_TICK_NEGATIVE = True
M15_SR_BLOCK_COUNTER_BIAS_SELL_IF_TICK_POSITIVE = True
M15_SR_ASIAN_COUNTER_BIAS_REQUIRE_A_PLUS = False
M15_SR_ASIAN_COUNTER_BIAS_MIN_TOUCHES = 3
M15_SR_ASIAN_COUNTER_BIAS_MIN_TICK_PRESSURE = 0.35
M15_SR_ASIAN_COUNTER_BIAS_MIN_CLOSE_POS = 0.75
M15_SR_ASIAN_COUNTER_BIAS_MAX_TRADES_PER_SESSION = 1
M15_SR_SIGNAL_TTL_SECONDS = 20
M15_SR_COUNTER_BIAS_SIGNAL_TTL_SECONDS = 10
M15_SR_MAX_ENTRY_DRIFT_ATR = 0.10
M15_SR_NORMAL_MIN_RR = 1.5
M15_SR_BOUNCE_MIN_RR = 0.8
M15_SR_BOUNCE_MAX_RR = 1.2
M15_SR_TRUE_REVERSAL_MIN_RR = 1.8
M15_SR_BOUNCE_MAX_HOLD_CANDLES = 4

# Centralized execution-quality scoring and confirmation gates
TRADE_SCORE_ENABLED = True
TRADE_SCORE_MIN = 75
TRADE_SCORE_PREMIUM = 85
TRADE_SCORE_RELAXED_MIN = 70
TRADE_SCORE_STRICT_AFTER_LOSS = 85

CONFIRMATION_3_OF_4_ENABLED = True

BLOCK_WEAK_COUNTER_TREND = True
COUNTER_TREND_MIN_SCORE = 85
COUNTER_TREND_REQUIRE_M15_ZONE = True
COUNTER_TREND_REQUIRE_SWEEP = True
COUNTER_TREND_REQUIRE_CANDLE_CONFIRMATION = True

# Safe auto-relax controls
AUTO_RELAX_ENABLED = False
AUTO_RELAX_AFTER_MINUTES = 90
AUTO_RELAX_MIN_SCORE = 70
AUTO_RELAX_RR = 1.4
AUTO_RELAX_ONLY_GOOD_SESSION = True
AUTO_RELAX_BLOCK_AFTER_LOSS = True
AUTO_RELAX_BLOCK_DRAWDOWN = True
AUTO_RELAX_REQUIRE_STABLE_SPREAD = True


_CONFIG_STATE_FILE = Path(__file__).with_name("runtime_config.json")
_CONFIG_PROFILES_FILE = Path(__file__).with_name("config_profiles.json")
_PERSISTED_KEYS = {
    "TRADING_ENABLED",
    "ANTI_MODE_ENABLED",
    "ANTI_MODE_CONTEXT_BLOCK_ENABLED",
    "ANTI_MODE_SL_MULTIPLIER", "ANTI_MODE_MAX_SL_POINTS",
    "ANTI_MODE_TP_MULTIPLIER", "ANTI_MODE_PROFIT_CHOKE_R",
    "M15_CANDLE_PROFIT_THROTTLE_ENABLED",
    "M15_CANDLE_PROFIT_THROTTLE_MIN_WINS",
    "M15_CANDLE_PROFIT_THROTTLE_MIN_PNL",
    "MAX_POSITIONS", "MAX_OPEN_TRADES", "MAX_RISK_PCT", "INTRADAY_RISK_PCT", "SWING_RISK_PCT",
    "MAX_DRAWDOWN_PCT", "MAX_LOT", "MIN_LOT",
    "DAILY_TARGET_DOLLARS", "DAILY_TARGET_ENABLED", "DAILY_LOSS_LIMIT_PCT",
    "DAILY_PROFIT_LOCK", "DAILY_PROFIT_LOCK_AFTER", "DAILY_MAX_LOSS", "DAILY_MAX_LOSS_PCT_OF_ACCOUNT",
    "MAX_CONSECUTIVE_LOSSES", "STOP_AFTER_CONSECUTIVE_LOSSES",
    "MIN_TRADE_COOLDOWN", "LOSS_STREAK_PAUSE",
    "SESSION_MAX_TRADES",
    "MARKET_TICK_POLL_INTERVAL", "DASHBOARD_WS_PUSH_INTERVAL",
    "CALENDAR_BLOCKING_ENABLED", "CALENDAR_BLOCK_BEFORE_MINUTES", "CALENDAR_BLOCK_AFTER_MINUTES",
    "DEFAULT_STRATEGY", "TIER1_ENABLED", "TIER1_SPREAD_RECHECK_MAX_DELTA",
    "TIER1_EARLY_FAIL_EXIT_ENABLED", "TIER1_EARLY_FAIL_TICKS",
    "TIER1_BLOCK_SPIKE_ENTRY", "TIER1_MAX_ENTRY_DELAY_MS",
    "SESSION_OVERRIDE_ENABLED",
    "SESSION_CENTRALIZED", "TRADE_ASIA_SESSION", "TRADE_CLOSED_SESSION",
    "TRADE_ROLLOVER", "PREMIUM_ONLY_ASIA",
    "ALL_GATES_OVERRIDE_ENABLED", "SPREAD_GATE_OVERRIDE_ENABLED",
    "COMPRESSION_GATE_OVERRIDE_ENABLED", "EXECUTION_GATE_OVERRIDE_ENABLED",
    "SWEEP_SKIP_M15_CONTEXT_GATE",
    "TIME_GATE_OVERRIDE_ENABLED", "SPREAD_MEAN_GATE_OVERRIDE_ENABLED",
    "SPREAD_VOLATILITY_GATE_OVERRIDE_ENABLED", "SPREAD_PERCENTILE_GATE_OVERRIDE_ENABLED",
    "SPREAD_DELTA_GATE_OVERRIDE_ENABLED", "COMPRESSION_RANGE_GATE_OVERRIDE_ENABLED",
    "ATR_RISING_GATE_OVERRIDE_ENABLED", "EXECUTION_QUALITY_GATE_OVERRIDE_ENABLED",
    "TICK_DIRECTION_GATE_OVERRIDE_ENABLED", "POST_SIGNAL_SPREAD_GATE_OVERRIDE_ENABLED",
    "XGB_BYPASS_ENABLED", "XGB_TRAINING_ENABLED", "XGB_BLOCKING_ENABLED",
    "XGB_BLOCK_THRESHOLD", "XGB_BLEND_CONFIDENCE_ENABLED", "XGB_LOG_CONFIDENCE_ENABLED",
    "AI_TRADE_ADVISOR_ENABLED", "AI_TRADE_ADVISOR_TIMEOUT_SECONDS",
    "AI_TRADE_ADVISOR_MIN_SECONDS_BETWEEN_CALLS", "AI_TRADE_ADVISOR_MAX_CONFIDENCE",
    "AI_TRADE_ADVISOR_SCORE_BUFFER", "AI_TRADE_ADVISOR_REJECT_CONFIDENCE_MIN",
    "AI_TRADE_ADVISOR_FAIL_OPEN",
    "SMC_SPREAD_MEAN_MAX", "SMC_SPREAD_STD_MAX", "SMC_SPREAD_PERCENTILE_MAX",
    "SMC_CURRENT_SPREAD_DELTA_MAX", "SCALPER_SPREAD_MEAN_MAX",
    "SCALPER_SPREAD_STD_MAX", "SCALPER_SPREAD_PERCENTILE_MAX",
    "SCALPER_CURRENT_SPREAD_DELTA_MAX", "COMPRESSION_RANGE_LOOKBACK",
    "COMPRESSION_ATR_MULTIPLIER", "SMC_THRESHOLD_WITH_TREND",
    "SMC_THRESHOLD_COUNTER", "SMC_THRESHOLD_COUNTER_MAX", "SMC_MIN_RR",
    "SMC_MIN_SETUP_CONDITIONS", "SMC_REQUIRE_M5_ALIGNMENT_SHORT",
    "SMC_TIMEFRAME_EMA_SLOPE_MIN", "SMC_LTF_TICK_CONFLICT_LONG_MAX",
    "SMC_LTF_TICK_CONFLICT_SHORT_MIN",
    "SMC_RANGING_THRESHOLD_OFFSET", "SMC_TRENDING_THRESHOLD_OFFSET",
    "SMC_EARLY_FAIL_POINTS", "SMC_EARLY_FAIL_RANGING", "SMC_EARLY_FAIL_TRENDING",
    "SMC_EARLY_FAIL_CONF_HIGH_MULT", "SMC_EARLY_FAIL_CONF_LOW_MULT",
    "SMC_TIER1_MIN_TICKS", "SMC_TIER1_MAX_TICKS", "SMC_TIER1_SPREAD_DELTA_MAX",
    "SWING_ENGINE_REVERSAL_MIN_PEAK_R", "SWING_ENGINE_REVERSAL_CANDLES_REQUIRED",
    "SWING_ENGINE_REVERSAL_BODY_THRESHOLD", "SWING_ENGINE_REVERSAL_HIGH_CONF_BODY",
    "SWING_ENGINE_REVERSAL_HIGH_CONF_MIN",
    "SWING_RECOVERY_MIN_PEAK_R", "SWING_RECOVERY_MIN_DIP_R", "SWING_RECOVERY_MIN_RECOVERY_R",
    "SWING_ENGINE_GIVEBACK_MIN_PEAK_R", "SWING_ENGINE_GIVEBACK_FLOOR_R",
    "SWING_PEAK_CAPTURE_ENABLED", "SWING_PEAK_CAPTURE_TRIGGER_R",
    "SWING_PEAK_CAPTURE_GIVEBACK_PCT", "SWING_PEAK_CAPTURE_MIN_LOCK_R",
    "SMC_HIGH_CONF_THRESHOLD", "SMC_HIGH_CONF_RR_MULTIPLIER", "SMC_HIGH_CONF_RISK_MULTIPLIER",
    "ADAPT_THRESHOLD_WTR_MIN", "ADAPT_THRESHOLD_WTR_MAX",
    "ADAPT_THRESHOLD_CTR_MIN", "ADAPT_THRESHOLD_CTR_MAX",
    "ADAPT_MIN_RR_MIN", "ADAPT_MIN_RR_MAX",
    "ADAPT_SESSION_TRADES_MIN", "ADAPT_SESSION_TRADES_MAX",
    "ADAPT_COOLDOWN_MIN", "ADAPT_COOLDOWN_MAX",
    "SCALPER_QUALITY_THRESHOLD", "SCALPER_SPEC_STRICT_MODE",
    "SCALPER_MARGINAL_QUALITY_MAX",
    "SCALPER_ATR_MIN", "SCALPER_ATR_MAX", "SCALPER_ATR_RATIO_MAX",
    "SCALPER_RSI_OVERSOLD_BLOCK", "SCALPER_RSI_OVERBOUGHT_BLOCK",
    "SCALPER_ASIAN_ATR_MIN", "SCALPER_ASIAN_EMA_SLOPE_MIN",
    "SCALPER_REQUIRE_PRESSURE_ALIGNMENT",
    "SCALPER_M15_TREND_REQUIRED", "SCALPER_M15_SLOPE_MIN",
    "SCALPER_EMA15_SLOPE_MIN", "SCALPER_EMA20_SLOPE_MIN",
    "SCALPER_BODY_RATIO_MIN", "SCALPER_BODY_VS_AVG_MIN", "SCALPER_TICK_DIR_THRESHOLD",
    "SCALPER_SWEEP_LOOKBACK", "SCALPER_SWEEP_TOLERANCE",
    "SCALPER_HARD_SPREAD_MAX", "SCALPER_MAX_CONSECUTIVE_LOSSES",
    "SCALPER_MICRO_TP_MIN", "SCALPER_MICRO_TP_MAX",
    "SCALPER_MICRO_SL_MIN", "SCALPER_MICRO_SL_MAX",
    "SCALPER_MAX_TRADES_SESSION", "SCALPER_LEVEL_COOLDOWN",
    "SCALPER_RANGE_EDGE_ENABLED", "SCALPER_RANGE_EDGE_LOOKBACK_CANDLES",
    "SCALPER_RANGE_EDGE_ENTRY_EDGE_ATR", "SCALPER_RANGE_EDGE_BOX_ATR_MIN",
    "SCALPER_RANGE_EDGE_BOX_ATR_MAX", "SCALPER_RANGE_EDGE_TP_MIN",
    "SCALPER_RANGE_EDGE_TP_MAX", "SCALPER_RANGE_MIN_ENTRY_VOLUME_RATIO",
    "SCALPER_BIAS_CONSOLIDATION_ENABLED", "SCALPER_BIAS_CONSOLIDATION_LOOKBACK_CANDLES",
    "SCALPER_BIAS_CONSOLIDATION_RANGE_ATR_MAX", "SCALPER_BIAS_CONSOLIDATION_CANDLE_RANGE_ATR_MAX",
    "SCALPER_BIAS_CONSOLIDATION_CLOSE_STD_ATR_MAX", "SCALPER_BIAS_CONSOLIDATION_ENTRY_EDGE_ATR",
    "SCALPER_BIAS_CONSOLIDATION_SL_BUFFER", "SCALPER_BIAS_CONSOLIDATION_TP_MIN",
    "SCALPER_BIAS_CONSOLIDATION_TP_MAX", "SCALPER_SIDEWAYS_RANGE_CONFIRM_ENABLED",
    "SCALPER_SIDEWAYS_RANGE_M30_REQUIRED", "SCALPER_SIDEWAYS_RANGE_OVERLAP_MIN",
    "SCALPER_MIN_ENTRY_VOLUME_RATIO", "SCALPER_ALLOW_ASIAN_SESSION",
    "SCALPER_ASIAN_MIN_ENTRY_VOLUME_RATIO", "SCALPER_ASIAN_QUALITY_THRESHOLD",
    "SCALPER_ASIAN_TICK_DIR_THRESHOLD", "SCALPER_ASIAN_REQUIRE_PRESSURE_ALIGNMENT",
    "SMC_MIN_ENTRY_VOLUME_RATIO",
    "BREAKEVEN_VOLUME_LOOKBACK_CANDLES",
    "TICK_PRESSURE_WINDOW_SECONDS", "TICK_PRESSURE_MAX_TICKS",
    "TICK_PRESSURE_ENTRY_BLOCK_THRESHOLD", "TICK_PRESSURE_SHORT_ENTRY_VETO_THRESHOLD",
    "TICK_PRESSURE_BREAKEVEN_HOLD_MIN",
    "TICK_PRESSURE_VELOCITY_EXIT_MAX",
    "M15_ZONE_MICRO_BIAS_ENABLED", "M15_ZONE_MICRO_BIAS_MIN_CONFIDENCE",
    "M15_ZONE_MICRO_BIAS_MIN_SCORE",
    "M15_ZONE_ROUTE_AGAINST_BIAS_TO_INVERSE", "M15_ZONE_BLOCK_NEUTRAL_BIAS",
    "M15_ZONE_SELL_REQUIRE_SHORT_PRESSURE", "M15_ZONE_SELL_MIN_NEGATIVE_PRESSURE_SCORE",
    "M15_ZONE_SELL_MIN_BODY_RATIO_IF_D1_UP", "M15_ZONE_SELL_BLOCK_IF_PRESSURE_LONG",
    "M15_ZONE_BUY_REQUIRE_LONG_PRESSURE", "M15_ZONE_BUY_MIN_BODY_RATIO_IF_D1_DOWN",
    "M15_ZONE_BUY_BLOCK_IF_PRESSURE_SHORT", "M15_ZONE_LOG_MICRO_BIAS_DETAILS",
    "M15_SCALP_FIXED_USD_TP_ENABLED", "M15_SCALP_FIXED_USD_TP",
    "M15_ZONE_ENFORCE_SIBLING_MUTEX", "POST_TIER1_REENTRY_COOLDOWN_SECONDS",
    "EXIT_PROFILE_SCALP_BE_TRIGGER_R", "EXIT_PROFILE_SCALP_BREAKEVEN_MIN_HOLD_SECONDS",
    "EXIT_PROFILE_SCALP_BREAKEVEN_VOLUME_HOLD_RATIO", "EXIT_PROFILE_SCALP_MIN_HOLD_SECONDS",
    "EXIT_PROFILE_SCALP_EARLY_FAIL_POINTS", "EXIT_PROFILE_SCALP_EARLY_FAIL_MIN_TICKS",
    "EXIT_PROFILE_SCALP_EARLY_FAIL_MAX_TICKS", "EXIT_PROFILE_SCALP_REVERSAL_ARM_R",
    "EXIT_PROFILE_SCALP_REVERSAL_DRAWDOWN_PCT", "EXIT_PROFILE_SCALP_REVERSAL_FLOOR_R",
    "EXIT_PROFILE_SCALP_PROFIT_LOCK_1_ARM_R", "EXIT_PROFILE_SCALP_PROFIT_LOCK_1_R",
    "EXIT_PROFILE_SCALP_PROFIT_LOCK_2_ARM_R", "EXIT_PROFILE_SCALP_PROFIT_LOCK_2_R",
    "EXIT_PROFILE_SCALP_TIMEOUT_SECONDS", "EXIT_PROFILE_SCALP_TIMEOUT_MIN_PROGRESS_R",
    "EXIT_PROFILE_SCALP_TRAIL_ACTIVATE_R", "EXIT_PROFILE_SCALP_TRAIL_LOCK_R",
    "EXIT_PROFILE_SCALP_VELOCITY_DROP_ENABLED",
    "EXIT_PROFILE_SMC_BE_TRIGGER_R", "EXIT_PROFILE_SMC_BREAKEVEN_MIN_HOLD_SECONDS",
    "EXIT_PROFILE_SMC_BREAKEVEN_VOLUME_HOLD_RATIO", "EXIT_PROFILE_SMC_MIN_HOLD_SECONDS",
    "EXIT_PROFILE_SMC_EARLY_FAIL_POINTS", "EXIT_PROFILE_SMC_EARLY_FAIL_MIN_TICKS",
    "EXIT_PROFILE_SMC_EARLY_FAIL_MAX_TICKS", "EXIT_PROFILE_SMC_REVERSAL_ARM_R",
    "EXIT_PROFILE_SMC_REVERSAL_DRAWDOWN_PCT", "EXIT_PROFILE_SMC_REVERSAL_FLOOR_R",
    "EXIT_PROFILE_SMC_TIMEOUT_SECONDS", "EXIT_PROFILE_SMC_TIMEOUT_MIN_PROGRESS_R",
    "EXIT_PROFILE_SMC_TRAIL_ACTIVATE_R", "EXIT_PROFILE_SMC_TRAIL_LOCK_R",
    "EXIT_PROFILE_SMC_VELOCITY_DROP_ENABLED",
    "EXIT_PROFILE_M15_BE_TRIGGER_R", "EXIT_PROFILE_M15_BREAKEVEN_MIN_HOLD_SECONDS",
    "EXIT_PROFILE_M15_BREAKEVEN_VOLUME_HOLD_RATIO", "EXIT_PROFILE_M15_MIN_HOLD_SECONDS",
    "EXIT_PROFILE_M15_EARLY_FAIL_POINTS", "EXIT_PROFILE_M15_EARLY_FAIL_MIN_TICKS",
    "EXIT_PROFILE_M15_EARLY_FAIL_MAX_TICKS", "EXIT_PROFILE_M15_REVERSAL_ARM_R",
    "EXIT_PROFILE_M15_REVERSAL_DRAWDOWN_PCT", "EXIT_PROFILE_M15_REVERSAL_FLOOR_R",
    "EXIT_PROFILE_M15_TIMEOUT_SECONDS", "EXIT_PROFILE_M15_TIMEOUT_MIN_PROGRESS_R",
    "EXIT_PROFILE_M15_TRAIL_ACTIVATE_R", "EXIT_PROFILE_M15_TRAIL_LOCK_R",
    "EXIT_PROFILE_M15_VELOCITY_DROP_ENABLED",
    "M15_SR_ENABLED", "M15_SR_AS_CONTEXT_ONLY", "M15_SR_LOOKBACK_HOURS", "M15_SR_FALLBACK_LOOKBACK_HOURS",
    "M15_SR_EXTENDED_LOOKBACK_HOURS",
    "M15_SR_MIN_TOUCHES", "M15_SR_ZONE_ATR_MULT", "M15_SR_ENTRY_BUFFER_ATR",
    "M15_SR_SL_BUFFER_ATR", "M15_SR_MIN_RR", "M15_SR_DEFAULT_RR",
    "M15_SR_MAX_SPREAD", "M15_SR_MAX_TRADES_PER_DAY",
    "M15_SR_COOLDOWN_CANDLES", "M15_SR_BLOCK_AFTER_SPIKE_CANDLES",
    "M15_SR_SPIKE_RANGE_ATR_MULT", "M15_SR_SPIKE_VOLUME_MULT",
    "M15_SR_MAX_DISTANCE_FROM_ZONE_ATR", "M15_SR_REQUIRE_CANDLE_CONFIRMATION",
    "M15_SR_SPIKE_ZONE_BYPASS",
    "TREND_CHANNEL_TOUCH_ATR_MULT", "TREND_CHANNEL_MIN_RR", "TRADE_SCORE_MIN", "TRADE_SCORE_PREMIUM",
    "TRADE_SCORE_RELAXED_MIN", "TRADE_SCORE_STRICT_AFTER_LOSS",
    "HTF_LONG_MANUAL_BIAS_ENABLED",
    "HTF_SHORT_MANUAL_BIAS_ENABLED",
    "CONFIRMATION_3_OF_4_ENABLED",
    "BLOCK_WEAK_COUNTER_TREND", "COUNTER_TREND_MIN_SCORE",
    "COUNTER_TREND_REQUIRE_M15_ZONE", "COUNTER_TREND_REQUIRE_SWEEP",
    "COUNTER_TREND_REQUIRE_CANDLE_CONFIRMATION",
    "AUTO_RELAX_ENABLED", "AUTO_RELAX_AFTER_MINUTES",
    "AUTO_RELAX_MIN_SCORE", "AUTO_RELAX_RR",
    "AUTO_RELAX_ONLY_GOOD_SESSION", "AUTO_RELAX_BLOCK_AFTER_LOSS",
    "AUTO_RELAX_BLOCK_DRAWDOWN", "AUTO_RELAX_REQUIRE_STABLE_SPREAD",
    "TRADE_WINDOW_LONDON_START", "TRADE_WINDOW_LONDON_END",
    "TRADE_WINDOW_OVERLAP_START", "TRADE_WINDOW_OVERLAP_END",
}
_DEFAULT_RUNTIME_CONFIG = {
    key: globals()[key]
    for key in sorted(_PERSISTED_KEYS)
    if key in globals()
}

_PROFILE_ROLES = {"live", "backtest"}
_PROFILE_SCOPES = {"shared", "live", "backtest"}
_PROFILE_ACTIVE = {"live": "live", "backtest": "live"}
_PROFILE_CACHE = {}


def get_runtime_defaults() -> dict:
    """Return code defaults before runtime_config.json overrides are applied."""
    return dict(_DEFAULT_RUNTIME_CONFIG)


def _sanitize_profile_name(name: str) -> str:
    text = str(name or "").strip()
    if not text:
        raise ValueError("Profile name is required")
    safe = []
    for ch in text:
        safe.append(ch if ch.isalnum() or ch in ("_", "-", ".") else "_")
    normalized = "".join(safe).strip("._-")
    if not normalized:
        raise ValueError("Profile name must contain letters or numbers")
    return normalized[:64]


def _normalize_profile_values(values: dict) -> dict:
    normalized = {}
    for key, value in (values or {}).items():
        if key in _PERSISTED_KEYS and key in globals():
            normalized[key] = value
    return normalized


def _default_profiles_payload() -> dict:
    defaults = get_runtime_defaults()
    return {
        "version": 1,
        "active_profiles": {"live": "live", "backtest": "live"},
        "profiles": {
            "live": {
                "name": "live",
                "description": "Current live trading profile",
                "scope": "live",
                "values": defaults,
            }
        },
    }


def _normalize_profile_scope(scope: str | None, fallback_name: str | None = None) -> str:
    text = str(scope or "").strip().lower()
    if text in _PROFILE_SCOPES:
        return text
    name = str(fallback_name or "").strip().lower()
    if name == "live":
        return "live"
    if name.startswith("backtest"):
        return "backtest"
    return "shared"


def _profile_matches_role(scope: str, role: str) -> bool:
    return scope == "shared" or scope == role


def _migrate_legacy_runtime_config() -> dict:
    payload = _default_profiles_payload()
    if not _CONFIG_STATE_FILE.exists():
        return payload
    try:
        legacy = json.loads(_CONFIG_STATE_FILE.read_text(encoding="utf-8"))
    except Exception:
        return payload
    live_values = dict(payload["profiles"]["live"]["values"])
    for key, value in legacy.items():
        if key in _PERSISTED_KEYS and key in live_values:
            live_values[key] = value
    payload["profiles"]["live"]["values"] = live_values
    return payload


def _load_profiles_payload() -> dict:
    global _PROFILE_CACHE, _PROFILE_ACTIVE
    payload = None
    if _CONFIG_PROFILES_FILE.exists():
        try:
            payload = json.loads(_CONFIG_PROFILES_FILE.read_text(encoding="utf-8-sig"))
        except Exception:
            payload = None
    if not isinstance(payload, dict):
        payload = _migrate_legacy_runtime_config()

    profiles = payload.get("profiles", {}) if isinstance(payload, dict) else {}
    if not isinstance(profiles, dict) or not profiles:
        profiles = _default_profiles_payload()["profiles"]

    normalized_profiles = {}
    for raw_name, raw_profile in profiles.items():
        try:
            name = _sanitize_profile_name(raw_name)
        except ValueError:
            continue
        values = _normalize_profile_values((raw_profile or {}).get("values", {}))
        if not values:
            values = get_runtime_defaults()
        normalized_profiles[name] = {
            "name": name,
            "description": str((raw_profile or {}).get("description", "")).strip(),
            "scope": _normalize_profile_scope((raw_profile or {}).get("scope"), fallback_name=name),
            "values": values,
        }
    if "live" not in normalized_profiles:
        normalized_profiles["live"] = {
            "name": "live",
            "description": "Current live trading profile",
            "scope": "live",
            "values": get_runtime_defaults(),
        }

    active_profiles = payload.get("active_profiles", {}) if isinstance(payload, dict) else {}
    normalized_active = {}
    for role in _PROFILE_ROLES:
        candidate = str(active_profiles.get(role, "")).strip() or ("live" if role == "live" else "live")
        if candidate not in normalized_profiles:
            candidate = "live"
        normalized_active[role] = candidate

    _PROFILE_CACHE = normalized_profiles
    _PROFILE_ACTIVE = normalized_active
    return {
        "version": 1,
        "active_profiles": dict(_PROFILE_ACTIVE),
        "profiles": copy.deepcopy(_PROFILE_CACHE),
    }


def _save_profiles_payload(payload: dict) -> dict:
    global _PROFILE_CACHE, _PROFILE_ACTIVE
    _CONFIG_PROFILES_FILE.write_text(json.dumps(payload, indent=2, sort_keys=True), encoding="utf-8")
    _PROFILE_CACHE = copy.deepcopy(payload.get("profiles", {}))
    _PROFILE_ACTIVE = dict(payload.get("active_profiles", {}))
    return payload


def list_runtime_profiles(role: str | None = None) -> dict:
    """Return persisted runtime profiles and active assignments."""
    payload = _load_profiles_payload()
    role_name = str(role or "").strip().lower()
    if role_name and role_name not in _PROFILE_ROLES:
        raise ValueError(f"Unknown profile role: {role_name}")
    profiles = copy.deepcopy(payload["profiles"])
    if role_name:
        profiles = {
            name: profile
            for name, profile in profiles.items()
            if _profile_matches_role(str(profile.get("scope", "shared")), role_name)
        }
    return {
        "active_profiles": dict(payload["active_profiles"]),
        "profiles": profiles,
        "profiles_by_role": {
            scoped_role: {
                name: copy.deepcopy(profile)
                for name, profile in payload["profiles"].items()
                if _profile_matches_role(str(profile.get("scope", "shared")), scoped_role)
            }
            for scoped_role in sorted(_PROFILE_ROLES)
        },
    }


def get_active_profile(role: str = "live") -> str:
    """Return the active profile name for the requested role."""
    role = str(role or "live").strip().lower()
    if role not in _PROFILE_ROLES:
        raise ValueError(f"Unknown profile role: {role}")
    _load_profiles_payload()
    return str(_PROFILE_ACTIVE.get(role, "live"))


def get_profile_values(name: str, role: str | None = None) -> dict:
    """Return persisted values for a named profile."""
    profile_name = _sanitize_profile_name(name)
    payload = _load_profiles_payload()
    profile = payload["profiles"].get(profile_name)
    if not profile:
        raise ValueError(f"Unknown profile: {profile_name}")
    if role:
        role_name = str(role).strip().lower()
        if role_name not in _PROFILE_ROLES:
            raise ValueError(f"Unknown profile role: {role_name}")
        if not _profile_matches_role(str(profile.get("scope", "shared")), role_name):
            raise ValueError(f"Profile {profile_name} is not available for role: {role_name}")
    return dict(profile.get("values", {}))


def _apply_runtime_values(values: dict) -> dict:
    applied = {}
    for key, value in (values or {}).items():
        if key in _PERSISTED_KEYS and key in globals():
            globals()[key] = value
            applied[key] = value
    return applied


def apply_runtime_profile(name: str, persist_role: str | None = None) -> dict:
    """Apply a named profile to in-memory config, optionally persisting a role selection."""
    profile_name = _sanitize_profile_name(name)
    payload = _load_profiles_payload()
    profile = payload["profiles"].get(profile_name)
    if not profile:
        raise ValueError(f"Unknown profile: {profile_name}")
    applied = _apply_runtime_values(profile.get("values", {}))
    if persist_role:
        role = str(persist_role).strip().lower()
        if role not in _PROFILE_ROLES:
            raise ValueError(f"Unknown profile role: {role}")
        if not _profile_matches_role(str(profile.get("scope", "shared")), role):
            raise ValueError(f"Profile {profile_name} is not available for role: {role}")
        payload["active_profiles"][role] = profile_name
        _save_profiles_payload(payload)
    return applied


def set_active_profile(role: str, name: str, apply_now: bool = False) -> dict:
    """Assign a profile to a role; optionally apply immediately to in-memory globals."""
    role_name = str(role or "").strip().lower()
    if role_name not in _PROFILE_ROLES:
        raise ValueError(f"Unknown profile role: {role_name}")
    profile_name = _sanitize_profile_name(name)
    payload = _load_profiles_payload()
    if profile_name not in payload["profiles"]:
        raise ValueError(f"Unknown profile: {profile_name}")
    profile = payload["profiles"][profile_name]
    if not _profile_matches_role(str(profile.get("scope", "shared")), role_name):
        raise ValueError(f"Profile {profile_name} is not available for role: {role_name}")
    payload["active_profiles"][role_name] = profile_name
    _save_profiles_payload(payload)
    if apply_now:
        return apply_runtime_profile(profile_name)
    return dict(payload["active_profiles"])


def save_runtime_profile(
    name: str | None = None,
    description: str | None = None,
    role_scope: str | None = None,
) -> dict:
    """Save current in-memory config into a named profile."""
    payload = _load_profiles_payload()
    profile_name = _sanitize_profile_name(name or get_active_profile("live"))
    current_values = {
        key: globals()[key]
        for key in sorted(_PERSISTED_KEYS)
        if key in globals() and key not in _ADAPTIVE_MANAGED_KEYS
    }
    existing = payload["profiles"].get(profile_name, {})
    scope = _normalize_profile_scope(
        role_scope if role_scope is not None else existing.get("scope"),
        fallback_name=profile_name,
    )
    payload["profiles"][profile_name] = {
        "name": profile_name,
        "description": str(description if description is not None else existing.get("description", "")).strip(),
        "scope": scope,
        "values": current_values,
    }
    _save_profiles_payload(payload)
    if profile_name == get_active_profile("live"):
        _CONFIG_STATE_FILE.write_text(
            json.dumps(current_values, indent=2, sort_keys=True),
            encoding="utf-8",
        )
    return copy.deepcopy(payload["profiles"][profile_name])


def create_runtime_profile(
    name: str,
    base_profile: str | None = None,
    description: str = "",
    role_scope: str | None = None,
) -> dict:
    """Create a new profile from defaults or from another profile."""
    payload = _load_profiles_payload()
    profile_name = _sanitize_profile_name(name)
    if profile_name in payload["profiles"]:
        raise ValueError(f"Profile already exists: {profile_name}")
    if base_profile:
        values = get_profile_values(base_profile)
    else:
        values = get_runtime_defaults()
    payload["profiles"][profile_name] = {
        "name": profile_name,
        "description": str(description or "").strip(),
        "scope": _normalize_profile_scope(role_scope, fallback_name=profile_name),
        "values": values,
    }
    _save_profiles_payload(payload)
    return copy.deepcopy(payload["profiles"][profile_name])


def delete_runtime_profile(name: str) -> dict:
    """Delete a saved profile if it is not active."""
    payload = _load_profiles_payload()
    profile_name = _sanitize_profile_name(name)
    if profile_name == "live":
        raise ValueError("The live profile cannot be deleted")
    if profile_name not in payload["profiles"]:
        raise ValueError(f"Unknown profile: {profile_name}")
    if profile_name in payload["active_profiles"].values():
        raise ValueError(f"Profile is active and cannot be deleted: {profile_name}")
    del payload["profiles"][profile_name]
    _save_profiles_payload(payload)
    return {"deleted": profile_name}


def update_runtime_profile(
    name: str,
    values: dict | None = None,
    description: str | None = None,
    role_scope: str | None = None,
) -> dict:
    """Update a profile's persisted values and/or description."""
    payload = _load_profiles_payload()
    profile_name = _sanitize_profile_name(name)
    if profile_name not in payload["profiles"]:
        raise ValueError(f"Unknown profile: {profile_name}")
    profile = payload["profiles"][profile_name]
    merged_values = dict(profile.get("values", {}))
    merged_values.update(_normalize_profile_values(values or {}))
    profile["values"] = merged_values
    if description is not None:
        profile["description"] = str(description).strip()
    if role_scope is not None:
        profile["scope"] = _normalize_profile_scope(role_scope, fallback_name=profile_name)
    else:
        profile["scope"] = _normalize_profile_scope(profile.get("scope"), fallback_name=profile_name)
    payload["profiles"][profile_name] = profile
    _save_profiles_payload(payload)
    return copy.deepcopy(profile)


def copy_profile_to_profile(
    source_name: str,
    target_name: str,
    target_scope: str | None = None,
    apply_if_active_live: bool = False,
) -> dict:
    """Copy all persisted values from one profile into another."""
    payload = _load_profiles_payload()
    source_profile_name = _sanitize_profile_name(source_name)
    target_profile_name = _sanitize_profile_name(target_name)
    source = payload["profiles"].get(source_profile_name)
    if not source:
        raise ValueError(f"Unknown source profile: {source_profile_name}")
    target = payload["profiles"].get(target_profile_name)
    if not target:
        raise ValueError(f"Unknown target profile: {target_profile_name}")
    target["values"] = dict(source.get("values", {}))
    target["scope"] = _normalize_profile_scope(
        target_scope if target_scope is not None else target.get("scope"),
        fallback_name=target_profile_name,
    )
    payload["profiles"][target_profile_name] = target
    _save_profiles_payload(payload)
    if apply_if_active_live and get_active_profile("live") == target_profile_name:
        apply_runtime_profile(target_profile_name)
    return copy.deepcopy(target)


def load_runtime_config(profile_name: str | None = None) -> dict:
    """Load a saved profile into in-memory globals."""
    target = profile_name or get_active_profile("live")
    return apply_runtime_profile(target)


# Keys managed by adaptive_params.py — written to cfg live each cycle but
# must NOT be persisted by save_runtime_config(), otherwise the adapted values
# overwrite the intended baseline in runtime_config.json.
_ADAPTIVE_MANAGED_KEYS = {
    "SMC_THRESHOLD_WITH_TREND", "SMC_THRESHOLD_COUNTER",
    "SMC_MIN_RR", "SESSION_MAX_TRADES", "MIN_TRADE_COOLDOWN",
    "SMC_SPREAD_MEAN_MAX", "SMC_EARLY_FAIL_RANGING", "SMC_EARLY_FAIL_TRENDING",
}


def save_runtime_config() -> dict:
    """Persist current config into the active live profile for the next restart."""
    profile = save_runtime_profile(get_active_profile("live"))
    return dict(profile.get("values", {}))


load_runtime_config()
